practice-for-ch-rails-ninety-nine-cats2-long-practice/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: :destroy do
    resources :cat_rental_requests, only: [:new]
  end
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

practice-for-ch-rails-ninety-nine-cats2-long-practice/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

practice-for-ch-rails-ninety-nine-cats2-long-practice/app/views/shared/_form.html.erb
<% action = (task == "signup" ? users_url : session_url) %>
<% message = (task == "signup" ? "Sign Up!" : "Log In!") %>

<form action="<%= action %>" method="POST">
  
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
  
  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    id="user_username"
  >
  <br>

  <label for="user_password">Password</label>
  <input 
    type="password"
    name="user[password]"
    id="user_password"
  >
  <br>

  <input type="submit" value="<%= message %>">
</form>